### PR TITLE
[NextDNS] optimistic update attempt 

### PR DESCRIPTION
**Pull request by xmok**
@pernielsentikaer instead of using onRemove and utils, why not pass the entire `mutate` to the list-item component and handle everything over there? This PR shows how we can achieve this.

### CODE REVIEW

**Comment by xmok** [comment]
In the lates commit we also have error handling for the case of "200 OK" yet an error.
Passing mutate directly to `list-item` will let us handle all the toggle, add, remove cases for both allowlist and denylist in single functions rather than use `onRemove` and similar in AllowList and DenyList separately. But we can also do it the way you have done - your call 💪.

**Comment by pernielsentikaer** [comment]
Your idea sounds more solid indeed, I might have forgot to pull before going ahead 🫠

**Comment by pernielsentikaer** [comment]
I should have started this in a branch for sure 🫠

**Comment by pernielsentikaer** [comment]
@xmok do you think you can help with the merge conflict, let's continue with your ideas

**Comment by xmok** [comment]
Yes I've checked out your latest changes locally first to review then I'll see the conflicts.

**Comment by pernielsentikaer** [comment]
Sorry about that, I like your idea better 🔥 You can also just push directly to main 🤖

**Comment by pernielsentikaer** [comment]
Maybe it's better to start over and move the files to a branch?

**Comment by pernielsentikaer** [comment]
You're da best

**Comment by xmok** [comment]
OK I think we're good to go. Had to mix and match some of the code but we're in a good place now. It can definitely be optimized but the main mutate functions seem to be working ok i.e I can add and toggle!

**Comment by pernielsentikaer** [comment]
Updated the code some more, it's starting to look pretty dope 🙂

**Pull request merged**
